### ISSUE TITLE
PA Review: New account creation, login, and guest/demo login

### ISSUE THREAD

**Issue by r-lee1** [r-lee1/scrollo#2]

**Comment by wongshington** [comment]
- [ ] not here

**Comment by r-lee1** [comment]
-[] fix sign up route

**Comment by r-lee1** [comment]
- [ ] fix signup route

**Comment by wongshington** [comment]
- [ ] add a little bit of margin between the login and demo button
- potentially you could add a small margin between the input fields
- [ ] try to center those errors, text align could be the key

**Comment by wongshington** [comment]
everything looks good!
