### ISSUE TITLE
PA Review:  Post form for various post types

### ISSUE THREAD

**Issue by r-lee1** [r-lee1/scrollo#4]
- [x] Users can create and edit posts in various post types
- [x] Post types consist of Text, Photo, Quote, Link, Audio, and Video
- [x] Post form pops up when a post type is selected
- [x] Post form is tailored to the post type

**Comment by wongshington** [comment]
- [ ] more unique styling of the quotes post type

**Comment by wongshington** [comment]
Looks good!
