### ISSUE TITLE
PA Review: Feed

### ISSUE THREAD

**Issue by r-lee1** [r-lee1/scrollo#5]
- [x] Users can view (index) posts
- [x] Feed populates with user's own posts and posts of followed users, starting with most recently posted

**Comment by r-lee1** [comment]
- [ ] Users can delete their own posts from the feed

**Comment by wongshington** [comment]
- [ ] shouldn't be able to submit an empty post

**Comment by wongshington** [comment]
- [ ] logo in the nav bar
