### ISSUE TITLE
PA Review: Follows

### ISSUE THREAD

**Issue by r-lee1** [r-lee1/scrollo#6]
- [x] Users can follow other users
- [x] A list of recommended users for the user to follow
- [x] When a user chooses to follow a user, the followed user's posts will appear on the feed
- [x] Users can unfollow followed users, the unfollowed user's posts will disappear from the feed

**Comment by wongshington** [comment]
errthang looks solid, see if you can figure out why it fires the "RECEIVE_POSTS" action twice if you have some time though
